version: '3.8'

services:
  backend:
    extends:
      file: ../bk/docker-compose.yml
      service: backend
    container_name: odds-comparison-backend

  frontend:
    extends:
      file: ../MarketEdge/docker-compose.yml
      service: frontend
    container_name: odds-comparison-frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5001

volumes:
  odds_data:
    name: odds_comparison_data 