version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odds-comparison-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:5001}
    restart: unless-stopped 